"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['video_on_tkinter_v2.py']
DATA_FILES = []
OPTIONS = {'argv_emulation':True,
           'packages':['cv2','pandas','tkinter','PIL.Image','PIL.ImageTk', 'importlib']}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
